#Odoo 15 CE 
version: '3.3'
services:
    odoo:
        container_name: odoo
        image: odoo:15.0
        volumes:
            - ./Odoo15CE/addons-extra:/mnt/extra-addons
            - ./Odoo15CE/etc/odoo:/etc/odoo
            - odoo-web-data:/var/lib/odoo
        ports:
            - "8069:8069"
            - "8000:8000"
        restart: always
        depends_on:
            - postgres
        environment:
            - MONGO_DB_IP=${MONGO_DB_IP}
    postgres:
        image: postgres:14
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - odoo-db-data:/var/lib/postgresql/data/pgdata          

volumes:
    odoo-web-data:
    odoo-db-data:


