version: '3.3'
services:
    stps_api_mongo1:
      container_name: stps_api_mongo1
      build: ./Final_Image/ApiMongoDB
      ports:
        - "3000:3000"
      volumes:
        - stps-api-data1:/app

    stps_api_mongo2:
      container_name: stps_api_mongo2
      build: ./Final_Image/ApiMongoDB
      ports:
        - "3001:3000"
      volumes:
        - stps-api-data2:/app

    stps_api_mongo3:
      container_name: stps_api_mongo3
      build: ./Final_Image/ApiMongoDB
      ports:
        - "3002:3000"
      volumes:
        - stps-api-data3:/app
volumes:    
    stps-api-data1:
    stps-api-data2:
    stps-api-data3: