version: "3"
services:
  nginx:
     image: nginx:1.15-alpine
     container_name: nginx_principal
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - ./data/nginx:/etc/nginx/conf.d
       - ./data/certbot/conf:/etc/letsencrypt
       - ./data/certbot/www:/var/www/certbot
     command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
     image: certbot/certbot
     volumes:
       - ./data/certbot/conf:/etc/letsencrypt
       - ./data/certbot/www:/var/www/certbot
     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  stps_api_nginx_load_balance1:
    image: nginx:alpine
    container_name: stps_api_nginx_load_balance1
    volumes:
      - ./data/load_balance.nginx.conf/nginx.stps_api_1.app.4gingenieria.com.conf:/etc/nginx/conf.d/z-overrides.conf

  stps_api_nginx_load_balance2:
    image: nginx:alpine
    container_name: stps_api_nginx_load_balance2
    volumes:
      - ./data/load_balance.nginx.conf/nginx.stps_api_2.app.4gingenieria.com.conf:/etc/nginx/conf.d/z-overrides.conf

  stps_api_nginx_load_balance3:
    image: nginx:alpine
    container_name: stps_api_nginx_load_balance3
    volumes:
      - ./data/load_balance.nginx.conf/nginx.stps_api_3.app.4gingenieria.com.conf:/etc/nginx/conf.d/z-overrides.conf
